
#include <stddef.h>
#include "flags.h"
// Brazil is defined in its own file for Reasons (it's too big to compile!)
#include "brazil.h"
// The autistic pride flag works the same as crabs, so it's in here. I'm sorry. 
#include "crabs.h" 
// Generated by py\sort_flags.py
extern Flag abrosexual_flag;
extern Flag aegosexual_flag;
extern Flag agender_flag;
extern Flag androgyne_flag;
extern Flag aroace_flag;
extern Flag aromantic_flag;
extern Flag asexual_flag;
extern Flag autistic_pride_flag;
extern Flag bear_flag;
extern Flag bigender_flag;
extern Flag bisexual_flag;
extern Flag black_queer_femme_flag;
extern Flag canada_pride_flag;
extern Flag crab_pride_flag;
extern Flag demiboy_flag;
extern Flag demigirl_flag;
extern Flag demiromantic_flag;
extern Flag demisexual_flag;
extern Flag disability_pride_flag;
extern Flag femme_lesbian_flag;
extern Flag five_stripe_gay_men_flag;
extern Flag five_stripe_lesbian_flag;
extern Flag gay_brazil_flag;
extern Flag gay_flag_of_south_africa;
extern Flag gay_men_flag;
extern Flag genderfluid_flag;
extern Flag genderflux_flag;
extern Flag genderqueer_flag;
extern Flag greysexual_flag;
extern Flag progressive_intersex_pride_flag;
extern Flag intersex_flag;
extern Flag jewish_pride_flag;
extern Flag labrys_flag;
extern Flag leather_flag;
extern Flag lipstick_lesbian_flag;
extern Flag lipstick_lesbian_colors_flag;
extern Flag littleender_flag;
extern Flag lydiandragon_lesbian_flag;
extern Flag maya_kern_lesbian_flag;
extern Flag neutrois_flag;
extern Flag nonbinary_flag;
extern Flag objectum_pride_flag;
extern Flag omnisexual_flag;
extern Flag original_rainbow_flag;
extern Flag pangender_pride_flag;
extern Flag pansexual_flag;
extern Flag philadelphia_pride_flag;
extern Flag pink_union_jack_flag;
extern Flag polyamory_flag;
extern Flag polysexual_flag;
extern Flag proculsexual_flag;
extern Flag progressive_flag;
extern Flag ps_slash_2_pride_flag;
extern Flag rainbow_flag;
extern Flag rubber_pride_flag;
extern Flag sadlesbeandisaster_lesbian_flag;
extern Flag seven_stripe_rainbow_flag;
extern Flag trains_flag;
extern Flag trans_pride;
extern Flag trans_crab_flag;
extern Flag tricolor_polyamory_pride_flag;
extern Flag voidpunk_pride_flag;

class Flag far *PRIDE_FLAGS[]={
	&abrosexual_flag,
	&aegosexual_flag,
	&agender_flag,
	&androgyne_flag,
	&aroace_flag,
	&aromantic_flag,
	&asexual_flag,
	&autistic_pride_flag,
	&bear_flag,
	&bigender_flag,
	&bisexual_flag,
	&black_queer_femme_flag,
	&canada_pride_flag,
	&crab_pride_flag,
	&demiboy_flag,
	&demigirl_flag,
	&demiromantic_flag,
	&demisexual_flag,
	&disability_pride_flag,
	&femme_lesbian_flag,
	&five_stripe_gay_men_flag,
	&five_stripe_lesbian_flag,
	&gay_brazil_flag,
	&gay_flag_of_south_africa,
	&gay_men_flag,
	&genderfluid_flag,
	&genderflux_flag,
	&genderqueer_flag,
	&greysexual_flag,
	&progressive_intersex_pride_flag,
	&intersex_flag,
	&jewish_pride_flag,
	&labrys_flag,
	&leather_flag,
	&lipstick_lesbian_flag,
	&lipstick_lesbian_colors_flag,
	&littleender_flag,
	&lydiandragon_lesbian_flag,
	&maya_kern_lesbian_flag,
	&neutrois_flag,
	&nonbinary_flag,
	&objectum_pride_flag,
	&omnisexual_flag,
	&original_rainbow_flag,
	&pangender_pride_flag,
	&pansexual_flag,
	&philadelphia_pride_flag,
	&pink_union_jack_flag,
	&polyamory_flag,
	&polysexual_flag,
	&proculsexual_flag,
	&progressive_flag,
	&ps_slash_2_pride_flag,
	&rainbow_flag,
	&rubber_pride_flag,
	&sadlesbeandisaster_lesbian_flag,
	&seven_stripe_rainbow_flag,
	&trains_flag,
	&trans_pride,
	&trans_crab_flag,
	&tricolor_polyamory_pride_flag,
	&voidpunk_pride_flag,
	NULL
};

