import re, os, glob


prideflags=[]
for filepath in glob.glob(os.path.join('..','*.cpp')):
	with open(filepath,'r') as f:
		data=f.read()
		seenfile=False
		for identifier,name in re.findall(r'^(?:static )?Flag ([a-z0-9_]+) = Flag\(\n\s*\"([^"]+)\"',data,re.DOTALL|re.MULTILINE):
			if not seenfile:
				seenfile=True
				print '{}:'.format(filepath)
			
			print ' * Found "{}"'.format(name)
			prideflags.append((name,identifier))

prideflags.sort()

with open(os.path.join('..','flagordr.h'),'w') as f:
	print >>f,'// Generated by py\\sort_flags.py'
	print >>f,'class Flag far *PRIDE_FLAGS[]={'
	for name, identifier in prideflags:
		print >>f,'\t&{},'.format(identifier)
	print >>f,'\tNULL\n};\n'