import os 
from extract_flags import extract_flags

prideflags = extract_flags()

with open(os.path.join('..','flagordr.cpp'),'w') as f:
	print("""
#include <stddef.h>
#include "flags.h"
// Brazil is defined in its own file for Reasons (it's too big to compile!)
#include "brazil.h"
// The autistic pride flag works the same as crabs, so it's in here. I'm sorry. 
#include "crabs.h" """,file=f)
	print('// Generated by py\\sort_flags.py',file=f)

	for name,identifier in prideflags:
		print('extern Flag {};'.format(identifier),file=f)


	print('\nclass Flag far *PRIDE_FLAGS[]={',file=f)
	for name, identifier in prideflags:
		print('\t&{},'.format(identifier),file=f)
	print('\tNULL\n};\n',file=f)